[settings]
legacy_version_file = true
#asdf_compat = true
trusted_config_paths = [
  '~/code',
]

[alias]
datadog-sbom-generator = 'ubi:datadog/datadog-sbom-generator'
datadog-static-analyzer = 'ubi:datadog/datadog-static-analyzer'
ftree = 'ubi:trinhminhtriet/ftree'
lscolors = 'ubi:sharkdp/lscolors'
oktaws = 'ubi:jonathanmorley/oktaws'
osv-scanner = 'ubi:google/osv-scanner'
scorecard = 'ubi:ossf/scorecard'
tlrc = 'aqua:tldr-pages/tlrc'
ldcli = 'ubi:launchdarkly/ldcli'
cai = "cargo:ad-si/cai"
clai = "ubi:baalimago/clai"

[env]
JAVA_8_HOME='/Users/bmontague/.local/share/mise/installs/java/corretto-8.392.08.1'
JAVA_11_HOME='/Users/bmontague/.local/share/mise/installs/java/corretto-11.0.18.10.1'
JAVA_17_HOME='/Users/bmontague/.local/share/mise/installs/java/corretto-17.0.7.7.1'

[tools]
actionlint = "latest"
age = "1.2.1"
amazon-ecr-credential-helper = "0.10.1"
awscli = "2.27.32"
cai = "latest"
clai = "latest"
container-structure-test = "1.17.0"
cosign = "2.5.0"
datadog-sbom-generator = "0.0.4"
datadog-static-analyzer = "latest"
delta = "0.18.2"
docker-slim = "1.41.7"
dust = "1.2.2"
ffmpeg = "7.1.1"
ftree = "0.1.2"
fzf = "0.62.0"
gh = "2.74.2"
glow = "latest"
hurl = "6.1.1"
hyperfine = "1.19.0"
java = "corretto-17.0.7.7.1"
jq = "1.8.0"
ldcli = "1.15.5"
lscolors = "0.20.0"
lsd = "1.1.5"
maven = "3.5.4"
node = "22.16.0"
oktaws = "0.19.1"
op = "2.30.3"
osv-scanner = "2.0.2"
packer = "1.13.1"
pnpm = "8.15.7"
python = "3.12.6"
ripgrep = "14.1.1"
ruby = "3.3.5"
ruff = "0.12.1"
rust = "1.87.0"
scorecard = "5.2.0"
terraform = "1.12.1"
tlrc = "1.11.1"
tokei = "12.1.2"
trivy = "0.63.0"
uv = "0.7.16"
vivid = "0.10.1"
yarn = "4.9.2"
yq = "4.45.4"
