[settings]
legacy_version_file = true
asdf_compat = true
trusted_config_paths = [
  '~/code',
]

[alias]
phrase = 'asdf:https://github.com/phrase/asdf-phrase'
datadog-static-analyzer = 'asdf:https://github.com/brentm5/asdf-datadog-static-analyzer.git'

[tools]
container-structure-test = "1.17.0"
ruby = "3.3.5"

[env]
JAVA_8_HOME='/Users/bmontague/.local/share/mise/installs/java/corretto-8.392.08.1'
JAVA_11_HOME='/Users/bmontague/.local/share/mise/installs/java/corretto-11.0.18.10.1'
JAVA_17_HOME='/Users/bmontague/.local/share/mise/installs/java/corretto-17.0.7.7.1'


